# Generated by Django 3.2.6 on 2021-08-17 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(help_text='Nome de Preferência', max_length=200)),
                ('faculdade', models.CharField(blank=True, help_text='Faculdade / Concursos', max_length=150)),
                ('objetivo', models.TextField(blank=True, help_text='Objetivos', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome Completo', max_length=200)),
                ('email', models.EmailField(help_text='Email', max_length=150)),
                ('cpf', models.CharField(help_text='CPF (somente números)', max_length=11)),
                ('telefone', models.CharField(help_text='Numero de telefone', max_length=30)),
                ('cep', models.CharField(help_text='CEP (somente números)', max_length=8)),
                ('referencia', models.CharField(blank=True, help_text='Referência', max_length=50)),
                ('endereco', models.CharField(help_text='Endereço', max_length=50)),
                ('numero_casa', models.CharField(help_text='Numero da casa', max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Complemento', max_length=50)),
                ('bairro', models.CharField(help_text='Bairro', max_length=30)),
                ('cidade', models.CharField(help_text='Cidade', max_length=30)),
                ('estado', models.CharField(help_text='Estado', max_length=30)),
                ('pais', models.CharField(help_text='Referência', max_length=30)),
                ('perfil', models.OneToOneField(help_text='Perfil Vinculado', on_delete=django.db.models.deletion.CASCADE, to='adc.perfil')),
            ],
        ),
    ]
